# Generated by Django 5.2.7 on 2025-10-19 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_kpis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sale",
            table="sale",
        ),
    ]
