# Generated by Django 5.1.3 on 2025-12-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_kpis", "0002_alter_sale_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "cac",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="CAC"
                    ),
                ),
                (
                    "ltv",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="LTV"
                    ),
                ),
                (
                    "arpu",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ARPU"
                    ),
                ),
                (
                    "churn_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Churn Rate %"
                    ),
                ),
                ("new_customers", models.IntegerField(verbose_name="Новых клиентов")),
                (
                    "active_customers",
                    models.IntegerField(verbose_name="Активных клиентов"),
                ),
                (
                    "marketing_spend",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Затраты на маркетинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика клиентов",
                "verbose_name_plural": "Метрики клиентов",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("location", models.CharField(max_length=200, verbose_name="Локация")),
                ("opened_date", models.DateField(verbose_name="Дата открытия")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.CreateModel(
            name="ShopMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Выручка"
                    ),
                ),
                (
                    "transactions_count",
                    models.IntegerField(verbose_name="Количество транзакций"),
                ),
                (
                    "customers_count",
                    models.IntegerField(verbose_name="Количество клиентов"),
                ),
                (
                    "avg_check",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Средний чек"
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="app_kpis.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Метрика магазина",
                "verbose_name_plural": "Метрики магазинов",
                "ordering": ["-date"],
                "unique_together": {("shop", "date")},
            },
        ),
    ]
