# Generated by Django 5.2.7 on 2025-12-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_kpis", "0003_customermetrics_shop_shopmetrics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="sale",
            name="shop",
            field=models.ForeignKey(
                db_column="shop_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="app_kpis.shop",
            ),
        ),
        migrations.AlterModelTable(
            name="sale",
            table="sales",
        ),
    ]
