# Generated by Django 5.1.3 on 2025-12-18 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_kpis", "0004_alter_sale_options_alter_sale_shop_alter_sale_table"),
    ]

    operations = [
        # Просто помечаем, что таблица уже существует
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,  # Ничего не делаем
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
