# Generated by Django 5.1.3 on 2025-12-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_kpis", "0005_sync_shop_with_db"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="location",
            field=models.CharField(max_length=200, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название магазина"),
        ),
        migrations.AlterModelTable(
            name="customermetrics",
            table="customer_metrics",
        ),
        migrations.AlterModelTable(
            name="shop",
            table="shop",
        ),
        migrations.AlterModelTable(
            name="shopmetrics",
            table="shop_metrics",
        ),
    ]
